Window:CreateLabel("Anime Punch Simulator")
Window:CreateLabel("Anime Dungeon Fighters")
Window:CreateLabel("One Fruit Simulator")
Window:CreateLabel("Pet Catchers")
Window:CreateLabel("Second Piece")
